services:
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      POSTGRES_DB: ${POSTGRES_DB:-dbs}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ${POSTGRES_DATA:-./postgres_data}:/var/lib/postgresql/data
    networks:
      - app_network

  # Tu aplicaci√≥n (ejemplo)
  # app:
  #   build: .
  #   container_name: my_app
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://admin:password123@postgres:5432/mydb
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge